version: "3.8"

networks:
  default:
    name: dwp-assessment-java-network

services:
  app:
    build:
      context: .
    container_name: dwp-assessment-java
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      PORT: ${PORT:-8080}
      CONTEXT_PATH: ${CONTEXT_PATH:-/}
      PEOPLE_ENDPOINT: ${PEOPLE_ENDPOINT:-http://wiremock:8080}
      MAX_DISTANCE: ${MAX_DISTANCE:-50}

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    command: --verbose
    ports:
      - 8090:8080
    volumes:
      - ./wiremock/files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
